const fs = require('fs');
const path = require('path');

// Writes to frontend/src/data/ — adjust path if your folder structure differs
const STATIC_DIR = path.join(__dirname, '../../frontend/src/data');

const ensureDir = () => {
  if (!fs.existsSync(STATIC_DIR)) {
    fs.mkdirSync(STATIC_DIR, { recursive: true });
  }
};

const syncPrograms = async (Program) => {
  try {
    ensureDir();
    const programs = await Program.find({ status: { $ne: 'draft' } })
      .sort('-date').select('-createdBy -__v').lean();

    const content = `// AUTO-GENERATED by FYC Admin Panel — DO NOT EDIT MANUALLY
// Last updated: ${new Date().toISOString()}
// To remove a program older than 5 days, delete it from this array and push to GitHub.

export const STATIC_PROGRAMS = ${JSON.stringify(programs, null, 2)};
`;
    fs.writeFileSync(path.join(STATIC_DIR, 'programs.js'), content, 'utf8');
    console.log(`✅ programs.js synced (${programs.length} items)`);
  } catch (err) {
    // On Vercel, filesystem writes are not persistent — this is expected
    console.warn('syncPrograms skipped (serverless env):', err.message);
  }
};

const syncCertificates = async (Certificate) => {
  try {
    ensureDir();
    const certs = await Certificate.find({}).sort('-createdAt').select('-__v').lean();

    const content = `// AUTO-GENERATED by FYC Admin Panel — DO NOT EDIT MANUALLY
// Last updated: ${new Date().toISOString()}
// To remove an award older than 5 days, delete it from this array and push to GitHub.

export const STATIC_CERTIFICATES = ${JSON.stringify(certs, null, 2)};
`;
    fs.writeFileSync(path.join(STATIC_DIR, 'certificates.js'), content, 'utf8');
    console.log(`✅ certificates.js synced (${certs.length} items)`);
  } catch (err) {
    console.warn('syncCertificates skipped (serverless env):', err.message);
  }
};

const syncBlogs = async (Blog) => {
  try {
    ensureDir();
    const blogs = await Blog.find({ status: 'published' }).sort('-createdAt').select('-__v').lean();

    const content = `// AUTO-GENERATED by FYC Admin Panel — DO NOT EDIT MANUALLY
// Last updated: ${new Date().toISOString()}
// To remove a blog older than 5 days, delete it from this array and push to GitHub.

export const STATIC_BLOGS = ${JSON.stringify(blogs, null, 2)};
`;
    fs.writeFileSync(path.join(STATIC_DIR, 'blogs.js'), content, 'utf8');
    console.log(`✅ blogs.js synced (${blogs.length} items)`);
  } catch (err) {
    console.warn('syncBlogs skipped (serverless env):', err.message);
  }
};

module.exports = { syncPrograms, syncCertificates, syncBlogs };
